// <auto-generated />
using EventHandler.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventHandler.Api.Data.Migrations.Booking
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20240729033657_Initial Booking Migration")]
    partial class InitialBookingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EventHandler.Api.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            EventId = 1,
                            Username = "andredubbs"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1,
                            EventId = 2,
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4,
                            EventId = 3,
                            Username = "janedoe"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3,
                            EventId = 4,
                            Username = "mikeross"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2,
                            EventId = 5,
                            Username = "sarahconnor"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 5,
                            EventId = 6,
                            Username = "bobsmith"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1,
                            EventId = 7,
                            Username = "alicesmith"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 3,
                            EventId = 8,
                            Username = "charliebrown"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 2,
                            EventId = 9,
                            Username = "davidjohnson"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 4,
                            EventId = 10,
                            Username = "emilywhite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
